version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_sp
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_DATABASE: sys
      MYSQL_ROOT_PASSWORD: coderslab
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
    ports:
      - "3308:3306"



  sprawdz-plan:
    image: sprawdz-plan
    container_name: sprawdz-plan_embeded

    ports:
      - "8080:8080"
    links:
      - mysql


